#
# local mysql & PhpMyAdmin
#
version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userstory
      MYSQL_USER: thomas-local # TODO: remove thomas-local user and just use root?
      MYSQL_PASSWORD: pass1
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'