#
# local mysql & PhpMyAdmin
#
version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_local
    environment:
      MYSQL_USER: thomas-local
      MYSQL_PASSWORD: pass1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_local
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '8183:80'